### PR TITLE
Added new hovering property to explore section

### LINKED ISSUE #10: Improve the footer.
You can improve the style of the footer by adding some more effects or information.

### PR DESCRIPTION
**Pull request by soumya-dash3**
## Thank you for your contribution to Dust-Road-Co 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Modified the explore section by updating hovering properties
2. Issue it resolves : #10 
3. GitHub Page Link : https://soumya-dash3.github.io/dustroadproject.github.io/index.html

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
Why you've opened another PR for the same issue? It already exists #59 @soumya-dash3

**Comment by soumya-dash3** [comment]
Actually some errors were occurring while making the PR in the previous branch so I made a new one. Is it ok? @2024-SANDHYA

**Review by 2024-SANDHYA — APPROVED** [review]

**Comment by soumya-dash3** [comment]
Can you please add the points for this in the scoresheet @2024-SANDHYA ?

**Comment by 2024-SANDHYA** [comment]
> Can you please add the points for this in the scoresheet @2024-SANDHYA ?

Sure, I'll by tomorrow. @soumya-dash3

**Comment by soumya-dash3** [comment]
Thanks @2024-SANDHYA

**Comment by soumya-dash3** [comment]
Did you update the score @2024-SANDHYA ?

**Pull request merged**
