### PR TITLE
added Testimonial section  

### LINKED ISSUE #41: Creating a testimonial slider section for reviews
It can be enhanced by adding a testimonial slider section for reviews using bootstrap.

### PR DESCRIPTION
**Pull request by sanjana317**
## Thank you for your contribution to Dust-Road-Co 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce: Added testimonial section for reviews
2. Issue it resolves: #41 
3. GitHub Page Link: https://sanjana317.github.io/Dust-Road-Co/

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@sanjana317 

1. Fix the alignment of the text here, see the existing website
image

2. Don't write "look what....", instead write "What our users say about our services?"
image

**Comment by sanjana317** [comment]
ohh okay thank you

**Comment by sanjana317** [comment]
@2024-SANDHYA I have made changes. Please take a look.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@sanjana317 There are some issues with padding or margin, this white space should not be their, check the existing website.

image

**Comment by sanjana317** [comment]
@2024-SANDHYA Yes, I made changes now. Please review it.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
This section should not be pure white, you may add some shade of white because the moment I scroll the navbar and this section looks one, which it shouldn't

image

@sanjana317

**Comment by sanjana317** [comment]
@2024-SANDHYA I have made changes but there seems to be a problem in the banner section which is why there's white space between the banner and the testimonial section. Please review it.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Add padding from the top of the content @sanjana317 
image

**Comment by sanjana317** [comment]
even after adding the padding, the white space is still there @2024-SANDHYA 
Screenshot 2022-01-11 184325

**Comment by 2024-SANDHYA** [comment]
> even after adding the padding, the white space is still there @2024-SANDHYA Screenshot 2022-01-11 184325

I know about that, I am not concerned about the white space. @sanjana317

**Comment by sanjana317** [comment]
@2024-SANDHYA oh okay I have added the padding and pushed the changes

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@sanjana317 Don't you think it's way too much ?

image

don't add too much I asked you for some.

**Comment by sanjana317** [comment]
oh sorry, I've changed it now @2024-SANDHYA

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Do half of this @sanjana317 
image

**Comment by sanjana317** [comment]
yes I have changed it @2024-SANDHYA

**Review by 2024-SANDHYA — APPROVED** [review]

**Pull request merged**
