### PR TITLE
added services section

### PR DESCRIPTION
**Pull request by suyogkokaje**
@2024-SANDHYA For resolving Issue #2 I have added 'services' section to the website. Currently the front side of the card is blank. I have put one empty img tag for each card. Add respective images in that. Also I have named all the services as 'Service' for now, and content as lorem ipsum.
<a href="https://suyogkokaje.github.io/Dust-Road-Co-Changes/">https://suyogkokaje.github.io/Dust-Road-Co-Changes/</a>
You can view the service section in the above website for demo.

### CODE REVIEW

**Comment by suyogkokaje** [comment]
Hello @2024-SANDHYA please have a look.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
It's not looking good @suyogkokaje  Please look on Behance or dribble for design inspiration also don't add it on a separate page, add the service section below the hero section only. Not on the diff page.

**Comment by suyogkokaje** [comment]
Okay. I will work on it.

**Comment by suyogkokaje** [comment]
First cards will be in this state

Screenshot-1350

and after we hover on them they will appear on screen with proper animation like  this 

Screenshot-1352

I will change the colour scheme according to our website, but is this design good? @2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
> First cards will be in this state
> 
> Screenshot-1350
> 
> and after we hover on them they will appear on screen with proper animation like this
> 
> Screenshot-1352
> 
> I will change the colour scheme according to our website, but is this design good? @2024-SANDHYA

No. Something like this :

image

**Comment by suyogkokaje** [comment]
Cool. Thanks

**Comment by suyogkokaje** [comment]
Hello @2024-SANDHYA I have made the suggested changes.  Please have a look.

**Comment by 2024-SANDHYA** [comment]
> Hello @2024-SANDHYA I have made the suggested changes. Please have a look.

It's looking very bad, leave it.

**Pull request closed without merging**
