### PR TITLE
The About us section has been created

### LINKED ISSUE #1: Create About Us section

### PR DESCRIPTION
**Pull request by radzhiv25**
## Thank you for your contribution to Dust-Road-Co 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : The change is that the About us section is added.
2. Issue it resolves : #1 issue is been resolved, which was for creating a about us section.
3. GitHub Page Link : https://radzhiv25.github.io/Dust-Road-Co/#

### CODE REVIEW

**Comment by radzhiv25** [comment]
This is my first contribution as well as PR so no worries if it gets rejected I will try my best to improve it more if needed

**Comment by 2024-SANDHYA** [comment]
No PRs accepted if you haven't written what's being asked in the template.

**Comment by radzhiv25** [comment]
> No PRs accepted if you haven't written what's being asked in the template.

is it ok now ?

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Not looking good. Linking read more to Wikipedia doesn't make sense. Please take some design inspiration from dribble or Behance. @radzhiv25 

image

**Comment by radzhiv25** [comment]
> Not looking good. Linking read more to Wikipedia doesn't make sense. Please take some design inspiration from dribble or Behance. @radzhiv25
> 
> image

how much time do i have so that i can work accordingly

**Comment by radzhiv25** [comment]
image
This type will be ok 
actually i am not able to relate with the topic so creating a about us is becoming a mess 
still i try more and update you again

**Comment by radzhiv25** [comment]
> image This type will be ok actually i am not able to relate with the topic so creating a about us is becoming a mess still i try more and update you again

just an update version all color and bg will be changed accordingly so just update me

**Comment by 2024-SANDHYA** [comment]
> image This type will be ok actually i am not able to relate with the topic so creating a about us is becoming a mess still i try more and update you again

No, not looking good. See some other websites, you can take some references from there. @radzhiv25

**Comment by radzhiv25** [comment]
> > image This type will be ok actually i am not able to relate with the topic so creating a about us is becoming a mess still i try more and update you again
> 
> No, not looking good. See some other websites, you can take some references from there. @radzhiv25

one last thing i wanted to know you want the section as grid based or flexbox based 
so that by today or tomorrow i will create the PR

**Pull request closed without merging**
