### PR TITLE
added hiring page

### LINKED ISSUE #43: Hiring-Page
### Description
Creating a we are hiring page for website.

### PR DESCRIPTION
**Pull request by AmanRana10**
## Thank you for your contribution to Dust-Road-Co 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Added hiring page
2. Issue it resolves : #43 
3. GitHub Page Link :  https://amanrana10.github.io/Dust-Road-Co/
Hiring page - Google Chrome 02-01-2022 13_19_34
Hiring page - Google Chrome 02-01-2022 13_19_48

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
Provide GitHub page link, not the screenshots please @AmanRana10

**Comment by AmanRana10** [comment]
Done @2024-SANDHYA

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
The design should be such that it should go with the website, in the website you created everything is clustered, no footer, no header completely different. I am not liking the design either. Please look for some design inspiration on Dribble or Behance.

**Comment by AmanRana10** [comment]
Ok will work on header...but I think the footer should be the same as that of the home page..also by clustered what do you mean exactly is it not responsive ??

**Comment by 2024-SANDHYA** [comment]
> Ok will work on header...but I think the footer should be the same as that of the home page..also by clustered what do you mean exactly is it not responsive ??

no no, clustered as in it's a bit messy and not organized @AmanRana10

**Comment by 2024-SANDHYA** [comment]
Been 8 days, you have 2 more days to create the PR @AmanRana10

**Comment by AmanRana10** [comment]
My end term is going on so i wouldn't be able to finish it...sorry @2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
> My end term is going on so i wouldn't be able to finish it...sorry @2024-SANDHYA

You are supposed to mention it then, it's your responsibility. @AmanRana10

**Pull request closed without merging**
