### PR TITLE
#45 work on preloader to the website preloader

### LINKED ISSUE #45: Work on pre-loader of the site
Add a minimalistic pre-loader to the website. Please assign me the task if that works :) @2024-SANDHYA

### PR DESCRIPTION
**Pull request by tiasaxena**
## Thank you for your contribution to Dust-Road-Co 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce: worked on improving the pre-loader to the website. The below short video shows the glimpse of it :)

  https://user-images.githubusercontent.com/89907755/147864472-86637a0b-fa60-475c-a8b0-e77a42d0b0cc.mp4

2. Issue it resolves :  #45 
3. GitHub Page Link :  https://tiasaxena.github.io/Dust-Road-Co/

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
> ## Thank you for your contribution to Dust-Road-Co 🤩🤩
> 
> [GitHub license](LICENSE) Open Source Love PRs Welcome
> 
> **Please mention the following in order to get PR merged** 🙌🏻🙌🏻
> 
>     1. Kind of change this PR introduce: worked on improving the pre-loader to the website. The below short video shows the glimpse of it :)
> 
> 
> preloader.mp4
> 
>     2. Issue it resolves :  [Work on pre-loader of the site #45](https://github.com/2024-SANDHYA/Dust-Road-Co/issues/45)
> 
>     3. GitHub Page Link :  https://tiasaxena.github.io/Dust-Road-Co/

It's not working @tiasaxena

**Comment by tiasaxena** [comment]
> > ## Thank you for your contribution to Dust-Road-Co 🤩🤩
> > [GitHub license](LICENSE) Open Source Love PRs Welcome
> > **Please mention the following in order to get PR merged** 🙌🏻🙌🏻
> > ```
> > 1. Kind of change this PR introduce: worked on improving the pre-loader to the website. The below short video shows the glimpse of it :)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > preloader.mp4
> > ```
> > 2. Issue it resolves :  [Work on pre-loader of the site #45](https://github.com/2024-SANDHYA/Dust-Road-Co/issues/45)
> > 
> > 3. GitHub Page Link :  https://tiasaxena.github.io/Dust-Road-Co/
> > ```
> 
> It's not working @tiasaxena

Ok! I'll figure out what the problem is because I can see it perfectly working at my end. Will get back soon @2024-SANDHYA

**Comment by tiasaxena** [comment]
Hello @2024-SANDHYA  :)
I re-worked the pre-loader and it's visible now for a noticeable time. It was not working before, maybe because the site doesn't have huge-sized elements. Thus, it didn't take time to load. But I resolved it now by adding time explicitly. You can review it from the link in PR :)
Let me know if that works😄 Thank You!

**Review by 2024-SANDHYA — COMMENTED** [review]
Looks nice and working fine, but I feel the existing one is apt for the website so ya @tiasaxena

**Comment by tiasaxena** [comment]
I re-worked and improved the design of the pre-loader. Please have a look and let me know 😄  @2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
It looks good, but I am liking the existing one much @tiasaxena

**Pull request closed without merging**
