### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by prachigarg19**
this is dashboard created using html,css.

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Provide me the GitHub page link to track the changes.

**Comment by prachigarg19** [comment]
> Provide me the GitHub page link to track the changes.
 
I don't know how to do this. Could you help me?

**Comment by 2024-SANDHYA** [comment]
> > Provide me the GitHub page link to track the changes.
> 
> I don't know how to do this. Could you help me?

Yes, go to your GitHub account repos. section where you've forked this repo, go to settings, 

image

then in the settings at the bottom you'll see this option click on that checkout here
image

select branch and root, click on save and provide me the published link that'll appear like this :


image



Still have any queries? Reach out to mentors that's what they are for :)

**Comment by 2024-SANDHYA** [comment]
Closing this, as no updates on the same @prachigarg19

**Pull request closed without merging**
